### Installing NUMPY 

In [2]:
pip install numpy

import numpy as np

### Numpy array inititialization 

In [13]:
my_list= [1,-7,5,0,9,98]

array = np.array(my_list,int)

print(array)

[ 1 -7  5  0  9 98]


### Attributes of Numpy array 

In [14]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [15]:
array2=array.reshape(3,2)

print(array2)

[[ 1 -7]
 [ 5  0]
 [ 9 98]]


In [17]:
array3= array.reshape(3,-1)

print(array3)

[[ 1 -7]
 [ 5  0]
 [ 9 98]]


In [18]:
my_list1 =[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

multi_array=np.array([my_list1,my_list2,my_list3])

print(multi_array)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [19]:
print(multi_array.shape)

(3, 5)


## Numpy arithematic operations 

In [23]:
x= np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [24]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [26]:
print(np.subtract(y,x))

[[4. 4.]
 [4. 4.]]


In [27]:
print(np.sum(x))

10.0


In [28]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [29]:
print(np.sum(x,axis=0))

[4. 6.]


In [30]:
print(np.sum(x,axis=1))

[3. 7.]


## More functions: 

In [ ]:
numpy.logaddexp -> Logarithm of sum of exponentaions of Input
numpy.truedivide -> returns a true division of inputs elementwise
numpy.floordivide -> Returns the largest integer smaller or equal to division of inputs
numpy.negative -> numerical negative element wise
numpy.power-> first array elements raised to powers of second array, element wise
numpy.remainder -> return element wise remainder of divison
numpy.mod -> return element wise remainder of division